webtalk_init -webtalk_dir /ad/eng/users/t/o/tobychen/Desktop/LAB ASSIGNMENT/Lab3-Task3/Lab3-Task3.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  5 19:54:10 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2014.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1071353" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_0_0_369" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bf078eb5-90e9-42ec-9e0a-e3bbbc2e06a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9aab9501-8a4e-4c47-98ac-2c6e0071c2d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.8 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0362D093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "02:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1049788413 -regid "211078688_0_0_369" -xml /ad/eng/users/t/o/tobychen/Desktop/LAB ASSIGNMENT/Lab3-Task3/Lab3-Task3.hw/webtalk/usage_statistics_ext_labtool.xml -html /ad/eng/users/t/o/tobychen/Desktop/LAB ASSIGNMENT/Lab3-Task3/Lab3-Task3.hw/webtalk/usage_statistics_ext_labtool.html -wdm /ad/eng/users/t/o/tobychen/Desktop/LAB ASSIGNMENT/Lab3-Task3/Lab3-Task3.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
