# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.cache/wt [current_project]
set_property parent.project_path /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.srcs/sources_1/new/ALU.v
  /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.srcs/sources_1/imports/Downloads/Top_module.v
}
read_xdc /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.srcs/constrs_1/imports/Downloads/Lab2_Task4_ALU_Constraints.xdc
set_property used_in_implementation false [get_files /ad/eng/users/t/o/tobychen/Desktop/Lab2-Task4/Lab2-Task4.srcs/constrs_1/imports/Downloads/Lab2_Task4_ALU_Constraints.xdc]

catch { write_hwdef -file Top_module.hwdef }
synth_design -top Top_module -part xc7a35tcpg236-1
write_checkpoint -noxdef Top_module.dcp
catch { report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb }
