# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.cache/wt [current_project]
set_property parent.project_path /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/movk.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/datamux.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/alumux.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/Reg2mux.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/imports/sources_1/imports/Downloads/Register_File.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/imports/sources_1/new/PC.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/imports/sources_1/imports/Downloads/IMem.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/imports/sources_1/new/Data_Memory.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/ControlUnit.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/imports/sources_1/imports/new/ALU.v
  /ad/eng/users/t/o/tobychen/Desktop/LABASSIGNMENT/Lab5_final_mux/Lab5_final.srcs/sources_1/new/Single_Cycle_Datapath.v
}
catch { write_hwdef -file Single_Cycle_Datapath.hwdef }
synth_design -top Single_Cycle_Datapath -part xc7a35tcpg236-1
write_checkpoint -noxdef Single_Cycle_Datapath.dcp
catch { report_utilization -file Single_Cycle_Datapath_utilization_synth.rpt -pb Single_Cycle_Datapath_utilization_synth.pb }
