# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Toby/Desktop/Lab3-Task3/Lab3-Task3.cache/wt [current_project]
set_property parent.project_path C:/Users/Toby/Desktop/Lab3-Task3/Lab3-Task3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Toby/Desktop/Lab3-Task3/Lab3-Task3.srcs/sources_1/new/wraparoundLEDS.v
read_xdc C:/Users/Toby/Desktop/Lab3-Task3/Lab3-Task3.srcs/constrs_1/new/wraparoundLEDSconstrain.xdc
set_property used_in_implementation false [get_files C:/Users/Toby/Desktop/Lab3-Task3/Lab3-Task3.srcs/constrs_1/new/wraparoundLEDSconstrain.xdc]

catch { write_hwdef -file wraparoundLEDS.hwdef }
synth_design -top wraparoundLEDS -part xc7a35tcpg236-1
write_checkpoint -noxdef wraparoundLEDS.dcp
catch { report_utilization -file wraparoundLEDS_utilization_synth.rpt -pb wraparoundLEDS_utilization_synth.pb }
